version: '3'

services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: gojgho-mysql57
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=gojgho-ecommerce-service
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb_unicode_ci']
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./docker/mysql/sql:/data/sql
  localstack:
    image: localstack/localstack:0.11.3
    container_name: gojgho-localstack-s3
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./docker/localstack:/tmp/localstack
      - ./docker/localstack/var/run/docker.sock:/var/run/docker.sock
    restart: always
