
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show-sql: true
        order_inserts: true
        order_updates: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce_service?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    auto-commit: false
    connectionTimeout: 3000
    idleTimeout: 0
    maxLifetime: 58000
    maximumPoolSize: 5

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.flywaydb: DEBUG

#MySQL의 8.x 버전 이후부터 발생하는 문제 allowPublicKeyRetrieval=true 로 설정 변경
