
ecommerce:
  domain:
    datasource:
      poolName: ecommerce-domain-cp
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: "jdbc:mysql://localhost:3306/ecommerce_service?useSSL=false&allowPublicKeyRetrieval=true"
      username: root
      password: root
      auto-commit: false
      sqlScriptEncoding: UTF-8
      connectionTimeout: 3000
      idleTimeout: 0
      maxLifetime: 58000
      maximumPoolSize: 5
    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
          show-sql: true
          order_inserts: true
          order_updates: true
          jdbc:
            batch_size: 500
            fetch_szie: 500
            batch_versioned_data: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.flywaydb: DEBUG
